### ISSUE TITLE
大佬很强啊，能加个联系方式膜拜下吗？

### ISSUE THREAD

**Issue by WMdoit** [k8gege/K8CScan#2]
方便留个联系方式吗？

**Comment by k8gege** [comment]
有BUG或建议反馈至此即可

**Comment by k8gege** [comment]
> 
> 
> 方便留个联系方式吗？

有BUG或建议反馈至此即可

**Comment by 1007172** [comment]
大佬 密码多少啊

**Comment by 8October8** [comment]
自定义参数不支持 >> 和 || ，可以优化一下吗？

**Comment by k8gege** [comment]
> 
> 自定义参数不支持 >> 和 || ，可以优化一下吗？
好的 感谢反馈

**Comment by k8gege** [comment]
>
> 自定义参数不支持 >> 和 || ，可以优化一下吗？

支持的调用cmd就行了,因效率问题,所以不是调用cmd后才执行命令
要执行多条命令，就得先调用cmd，其它命令自身不支持特殊符号
[Cscan]
exe=cmd.exe
arg=/c ping -n 1 $ip$ | find "ms" >> C:\Users\k8gege\Desktop\Cscan\1.txt

**Comment by takumi913** [comment]
k8大佬，没想到你居然把工具放到github了，以前经常看你的博客，佩服的不行
