### ISSUE TITLE
如何安装

### ISSUE THREAD

**Issue by tlhszc** [k8gege/K8CScan#5]
软件包下载下来后，是在python下运行？
是在win还是linux下运行？

**Comment by k8gege** [comment]
> 
> 
> 软件包下载下来后，是在python下运行？
> 是在win还是linux下运行？

无需安装
https://github.com/k8gege/K8CScan/wiki/3.Usage

**Comment by tlhszc** [comment]
> > 软件包下载下来后，是在python下运行？
> > 是在win还是linux下运行？
> 
> 无需安装
> https://github.com/k8gege/K8CScan/wiki/3.Usage

没有发现Cscan.exe文件，win10下可以使用吗？运行CscanGui,会在cmd窗口中报错。
解压了k8cscan5.2.rar,cmd中运行，提示如下：
Cscan 5.2
By K8gege
Not Found Cscan.ini or DllMoudle or scan.exe
Default View Online PC
****
Finished!
这个有结果输出吗？

**Comment by k8gege** [comment]
> 
> 
> > > 软件包下载下来后，是在python下运行？
> > > 是在win还是linux下运行？
> > 
> > 
> > 无需安装
> > https://github.com/k8gege/K8CScan/wiki/3.Usage
> 
> 没有发现Cscan.exe文件，win10下可以使用吗？运行CscanGui,会在cmd窗口中报错。
> 解压了k8cscan5.2.rar,cmd中运行，提示如下：
> Cscan 5.2
> By K8gege
> Not Found Cscan.ini or DllMoudle or scan.exe
> Default View Online PC
> 
> Finished!
> 这个有结果输出吗？

改名即可,Win10用4.x版本,默认通过ICMP扫描存活主机。
如果系统PING不通内网机器的话，可能默认防火墙拦了。
ping不通机器，程序也会扫不到(ping也是基于ICMP协议)

输出结果除了密码爆破模块,其它模块需重定向输出文件

**Comment by ekko12** [comment]
请问下工具的解压密码是什么
